[package]
name = "bench-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
fs2.workspace = true
crc32fast.workspace = true
rafter = { git = "https://github.com/zsumz/rafter", rev = "1d4befde820ad58e2638133faf8949fc3c1342a3" }
rafter-runtime = { git = "https://github.com/zsumz/rafter", rev = "1d4befde820ad58e2638133faf8949fc3c1342a3" }
