[package]
name = "raft-bench-rafter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
journal-hard-state = []
wal-hard-state = []
peer-group-commit = []
ordered-apply = []
pipelined-durability = ["peer-group-commit", "ordered-apply"]

[dependencies]
bench-common.workspace = true
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
rafter = { git = "https://github.com/zsumz/rafter", rev = "ad9543355fa0b6f29b8ea64abd3ab0d790d3cba1" }
rafter-runtime = { git = "https://github.com/zsumz/rafter", rev = "ad9543355fa0b6f29b8ea64abd3ab0d790d3cba1" }
rafter-storage = { git = "https://github.com/zsumz/rafter", rev = "ad9543355fa0b6f29b8ea64abd3ab0d790d3cba1" }
rafter-codec = { git = "https://github.com/zsumz/rafter", rev = "ad9543355fa0b6f29b8ea64abd3ab0d790d3cba1" }
