[package]
name = "raft-bench-rafter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
journal-hard-state = []
wal-hard-state = []
peer-group-commit = []
ordered-apply = []
pipelined-durability = ["peer-group-commit", "ordered-apply"]

[dependencies]
bench-common.workspace = true
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
rafter = { git = "https://github.com/zsumz/rafter", rev = "fa96cd4fa8cbccefa0a6c74046026137b102ce9f" }
rafter-runtime = { git = "https://github.com/zsumz/rafter", rev = "fa96cd4fa8cbccefa0a6c74046026137b102ce9f" }
rafter-storage = { git = "https://github.com/zsumz/rafter", rev = "fa96cd4fa8cbccefa0a6c74046026137b102ce9f" }
rafter-codec = { git = "https://github.com/zsumz/rafter", rev = "fa96cd4fa8cbccefa0a6c74046026137b102ce9f" }
